# Generated by Django 5.0.3 on 2024-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=9)),
                ('photo', models.ImageField(upload_to='registros/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombreCompleto', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es un Supervisor')),
                ('tipo', models.CharField(default='cliente', max_length=16, verbose_name='Tipo de Usuario')),
                ('direccion', models.CharField(default='', max_length=60, verbose_name='Dirrecion')),
                ('ciudad', models.CharField(default='', max_length=25, verbose_name='Ciudad')),
                ('telefono', models.CharField(default='', max_length=25, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_usuario_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_usuario_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
