# Generated by Django 5.0.3 on 2024-05-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido'),
        ),
    ]
