# Generated by Django 5.0.3 on 2024-05-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarios_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(default='Accesorios', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='photo',
            field=models.ImageField(upload_to='inventario/'),
        ),
    ]
