# Generated by Django 4.2.1 on 2024-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inventario_categoria_alter_inventario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='photo',
            field=models.ImageField(upload_to='accesorios/inventario/'),
        ),
    ]

