# Generated by Django 4.2.1 on 2024-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_inventario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('accesorios', 'Accesorios'), ('equipamento', 'Equipamentos'), ('vehiculos', 'Vehiculos'), ('repuestos', 'Repuestos'), ('aditamentos', 'Aditamentes')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='photo',
            field=models.ImageField(upload_to='inventario/'),
        ),
    ]
