# Generated by Django 4.2.1 on 2024-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_inventario_categoria_alter_inventario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='sub_categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('automatica', 'automatica'), ('enduro', 'enduro'), ('superdeportivas', 'superdeportivas'), ('deportivas', 'deportivas'), ('urbanas', 'urbanas'), ('todoterreno', 'todoterreno')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.CharField(max_length=13),
        ),
    ]
