# Generated by Django 5.0.3 on 2024-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventario_sub_categoria_alter_inventario_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('accesorios', 'accesorios'), ('equipamento', 'equipamento'), ('vehiculos', 'vehiculos'), ('repuestos', 'repuestos'), ('aditamenes', 'aditamenes')], default='', max_length=32),
        ),
    ]
