# Generated by Django 5.0.3 on 2024-05-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_inventario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.CharField(max_length=60),
        ),
    ]
