# Generated by Django 5.0.3 on 2024-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_inventario_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=800),
        ),
    ]
