# Generated by Django 4.2.1 on 2024-05-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_inventario_descripcion_alter_inventario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='sub_categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('automatica', 'automatica'), ('enduro', 'enduro'), ('superdeportivas', 'superdeportivas'), ('deportivas', 'deportivas'), ('urbanas', 'urbanas'), ('todoterreno', 'todoterreno'), ('cuatrimotos', 'cuatrimotos')], default='', max_length=32),
        ),
    ]
