# Generated by Django 5.0.3 on 2024-05-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_inventario_sub_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('direccion', models.CharField(default='', max_length=60, verbose_name='Dirrecion')),
                ('ciudad', models.CharField(default='', max_length=25, verbose_name='Ciudad')),
                ('telefono', models.CharField(default='', max_length=25, verbose_name='Telefono')),
                ('mensaje', models.TextField()),
                ('objeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventario')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
    ]
