# Generated by Django 4.2.1 on 2024-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cilindraje',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='peso',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='potenciaMaxima',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipoDeMotor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='torqueMaximo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='sub_categoria',
            field=models.CharField(blank=True, choices=[('', ''), ('automatica', 'Automatica'), ('enduro', 'Enduro'), ('superdeportivas', 'Superdeportivas'), ('deportivas', 'Deportivas'), ('urbanas', 'Urbanas'), ('todoterreno', 'Todoterreno'), ('cuatrimotos', 'Cuatrimotos')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(default='', max_length=16, verbose_name='Tipo de Usuario'),
        ),
    ]
