# Generated by Django 4.2.7 on 2025-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_inventario_cilindraje_inventario_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tipoDeMotor',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
