# Generated by Django 4.2.7 on 2025-09-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20250929_2332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='carritoitem',
            name='unique_user_product',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='notificaciones',
            field=models.BooleanField(default=False, verbose_name='Recibir notificaciones por correo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(default='cliente', max_length=16, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('usuario', 'producto')},
        ),
    ]
