# Generated by Django 4.2.7 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_metodopago_venta_numero_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
