from django.conf import settings
from django.urls import path 
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('redireccionar/', redireccionar_usuario, name='redireccionar_usuario'),
    path('motocicletas/', motocicletas, name='motocicletas'),
    path('accesorios/', accesorios, name='accesorios'),
    path('repuestos/', repuestos, name='repuestos'),
    path('search/', search, name='search'),
    path('enduro/', enduro, name='enduro'),
    path('todoterreno/', todoterreno, name='todoterreno'),
    path('urbanas/', urbanas, name='urbanas'),
    path('deportivas/', deportivas, name='deportivas'),
    path('automatica/', automaticas, name='automatica'),
    path('superdeportivas/', superdeportivas, name='superdeportivas'),
    path('equipamentos/', equipamentos, name='equipamentos'),
    path('aditamenes/', aditamenes, name='aditamenes'),
    path('cuatrimotos/', cuatrimotos, name='cuatrimotos'),
    path('VerMas/<int:pk_object>', vermas, name='vermas'),
    path('contactar/', contacto, name='contactar'),
    path('perfil/', perfil, name='perfil'),
    path('notificaciones/', notificaciones, name='notificaciones'),
    path('carrito/', carrito, name='carrito'),
    path('carrito/ver/', ver_carrito, name='ver_carrito'),
    path('carrito/agregar/<int:pk_object>/', agregar_al_carrito, name='agregar_al_carrito'),
    path('carrito/quitar/<int:pk_object>/', quitar_del_carrito, name='quitar_del_carrito'),
    path('carrito/actualizar/<int:pk_object>/', actualizar_cantidad_carrito, name='actualizar_cantidad_carrito'),
    path('carrito/finalizar/', finalizar_compra, name='finalizar_compra'),
    path('comprar/<int:pk_object>/', comprar, name='comprar'),
    path('compra-exitosa/', compra_exitosa, name='compra_exitosa'),

    path('cotizar/<int:pk_object>/', cotizar, name='cotizar'),
    path('vendedor/', vendedor, name='vendedor'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin/inventario/', admin_inventario, name='admin_inventario'),
    path('admin/inventario/crear/', inventario_crear, name='inventario_crear'),
    path('admin/inventario/editar/<int:pk>/', inventario_editar, name='inventario_editar'),
    path('admin/inventario/eliminar/<int:pk>/', inventario_eliminar, name='inventario_eliminar'),
    path('admin/usuarios/', admin_usuarios, name='admin_usuarios'),
    path('admin/usuarios/crear/', usuario_crear, name='usuario_crear'),
    path('admin/usuarios/editar/<int:pk>/', usuario_editar, name='usuario_editar'),
    path('admin/usuarios/eliminar/<int:pk>/', usuario_eliminar, name='usuario_eliminar'),
    path('admin/reportes/', reportes_pdf, name='reportes_pdf'),
    path('admin/reportes/ventas-pdf/', generar_reporte_ventas_pdf, name='generar_reporte_ventas_pdf'),
    path('admin/reportes/inventario-pdf/', generar_reporte_inventario_pdf, name='generar_reporte_inventario_pdf'),
    path('admin/insumos/', admin_insumos, name='admin_insumos'),
    path('admin/insumos/crear/', insumo_crear, name='insumo_crear'),
    path('admin/insumos/editar/<int:pk>/', insumo_editar, name='insumo_editar'),
    path('admin/insumos/eliminar/<int:pk>/', insumo_eliminar, name='insumo_eliminar'),
    path('admin/metodos-pago/', admin_metodos_pago, name='admin_metodos_pago'),
    path('admin/metodos-pago/crear/', metodo_pago_crear, name='metodo_pago_crear'),
    path('admin/metodos-pago/editar/<int:pk>/', metodo_pago_editar, name='metodo_pago_editar'),
    path('admin/metodos-pago/eliminar/<int:pk>/', metodo_pago_eliminar, name='metodo_pago_eliminar'),
    path('vendedor/venta/', vendedor_venta, name='vendedor_venta'),
    path('carrito/finalizar/', finalizar_compra, name='finalizar_compra'),
    
]
